sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.2)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token:
      secure: s0aNqb54/0Xf7kN9cWDuTA3v7JaoJyDdyWG66YzgJvIcMnK9qouVRZjsymTYRNX0JK+8iDtRLT2zL+Uxcp8SF1ePHE7LqNAQ0fNp+ry/aaldeCLxOfnt9qdjwGSmcf2Xq5DELxn31N8GK/gMK+8AURpE3umtatgG1tzfF3PipunaYUvwneb3EnTPKqD3hjPCwO+o4dawQZMRTruMXqEl2on4obrfepjhpsx/hovUykIJUSFNrq0DjTR5Tc6SPcwQH+dFisN8v4j41I6qlzg9mWlO68vsSXd7OQuv/5VYDqh0iXYmlfh4gjGxRgkw0kg2/NHX7J4ppz7PIvoBv5G4MLjujT4FBPDvrlmmL2kxFkOaHf72MMmkc6RTggUB3Ro2sUzYy/KT9hbyCd3G3hDUz4CPpTYrdEhtir+ced86icO+sofcaY3S7D9WA5PBhMzSfE8tWJKKbqwPlATwxCKjZBN0+WqhzpXspCwp/OkTt/0s0Ll8pzSkZco5BpHJW393HSy2hvnOlGg69Qxcasg8toEttjCbXKxYwyv9ordxOlytlVlhhTrzjOp5qxLkQzGkXM0UzJBIkFAii5sP/JsDOySepe9N+5AztMLOSWwYZyYJ9S8OroR8qeGLc9jwNNPwPiuBkYNxAwI9Q+ebv8jvqAG0pegQKW9F3bjpNOqnr9k=
