sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.2)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token:
      secure: VECAiBGbd6jUe1BdPyR/ggIYj6GbUWYJtfq7WSs29OWkK/ijWyxZJUvx0n25d0oeReCXHq1fG7CI4VkpX4MBlIikOYcjCTz78fAN5HkwMTcfvXMrCgbGNLICFbVPvX3mQnSR2rbyfSytUAiMBre9ESnzRAlMqdGk6zDj7hyjo/WA0cDg9spbObxzSdSl3y6QAcexNKzX1s6J5hX3Pyl/XGEMjiI48KwBIvlwBR6EGTZA4vBQXfCUxp03ESegMut123AsLLB+qqy+7xv10TADgd9wdBmb26ijkYh383LrIKX5OrzpQgLumOEVF8lt2Yc8gGLBQGp9OJe3EA3NTRneXzzYcId9TTOPgT43926sgl7MGU+5XFw5ECN2ck8zb+/rhDAHtgHvZy03PS7tq/IyRF5jpOVocBZdvJ9suzKJxvXtV8W0SfofdQejZINCBSm9g/1PDPnrnhzsQVFc2dDHDZs1i9EUX5uUgtqEF9yrH7CIw6sknt/GVCRnuthy7radlGKdP5CI20YmcPZfDZzDlaQPxPeZIX2rieKKc7rmCLHuvUIPMkSG2YgfzeXdwLchNVZebYLISzu7aAjT+SLGF/yliPY2+qz6rz7yoEII5fmq99vG5pLgopmw9DY4/Gp2zPstubJdZKx9pQCmB/djALdsmL0sRTNYLIrbzp/KyqU=
